spring:
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  application:
    name: hr_manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/human_resources_db?useSSL=false
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true